### ISSUE TITLE
Add support for other programs.

### ISSUE THREAD

**Issue by ghost** [BrunoPanizzi/stockPrices#1]
I really like the simplicity yet effectiveness of your program, I wonder if you could make this for other spreadsheet programs, and does it work on Linux, happy to test it for you.

`wbPath = 'path to the Workbook'`

If I were to put a Linux path such as -/home/guest/documents/example.xlsx would it work

`
	# gets the stock price from yahoo finance	
price = web.DataReader(stock, data_source='yahoo', start=today, end=today)	
price = round(price['Close'][today], 2)  # rounding the number`

What if you changed the source so it was not yahoo finance?

**Comment by ntbk1919** [comment]
I'm not the author, but yeah Linux should work, it's a simple program.
And other sources that code might not work, because its written for the way in which Yahoo Finance returns the data.

**Comment by ghost** [comment]
> I'm not the author, but yeah Linux should work, it's a simple program.
> And other sources that code might not work, because its written for the way in which Yahoo Finance returns the data.

Ok thank you!
