### ISSUE TITLE
Requirements. txt 

### ISSUE THREAD

**Issue by ntbk1919** [BrunoPanizzi/stockPrices#2]
Please add Requirements. txt.

**Comment by danger-ahead** [comment]
I can help with that! Would you mind assigning me @BrunoPanizzi ?

**Comment by BrunoPanizzi** [comment]
> I can help with that! Would you mind assigning me @BrunoPanizzi ?

Just go for it!

**Comment by danger-ahead** [comment]
@ntbk1919 @BrunoPanizzi issue fixed 👍
consider merging my pull request.
